import type { Customer, Product, ChatConversation, ChatbotRecord } from "./types"

export const mockCustomers: Customer[] = [
  {
    id: "c1",
    name: "Ana Rodríguez",
    email: "ana.rodriguez@email.com",
    phone: "+52 555 123 4567",
    source: "Facebook Ads",
    createdAt: "2026-01-15T10:30:00",
    status: "active",
  },
  {
    id: "c2",
    name: "Pedro Sánchez",
    email: "pedro.sanchez@email.com",
    phone: "+52 555 234 5678",
    source: "Google Ads",
    createdAt: "2026-01-20T14:20:00",
    status: "active",
  },
  {
    id: "c3",
    name: "Laura Fernández",
    email: "laura.f@email.com",
    phone: "+52 555 345 6789",
    source: "Instagram Ads",
    createdAt: "2026-01-22T09:15:00",
    status: "pending",
  },
  {
    id: "c4",
    name: "Roberto Díaz",
    email: "roberto.diaz@email.com",
    phone: "+52 555 456 7890",
    source: "Facebook Ads",
    createdAt: "2026-01-25T16:45:00",
    status: "inactive",
  },
  {
    id: "c5",
    name: "Carmen Morales",
    email: "carmen.m@email.com",
    phone: "+52 555 567 8901",
    source: "Referido",
    createdAt: "2026-01-27T11:00:00",
    status: "active",
  },
]

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Seguro de Vida Premium",
    description: "Cobertura completa con beneficios extendidos para toda la familia",
    price: 2500,
    category: "Seguros",
    stock: 999,
    status: "active",
  },
  {
    id: "p2",
    name: "Plan de Inversión Básico",
    description: "Inversión segura con rendimientos garantizados del 8% anual",
    price: 5000,
    category: "Inversiones",
    stock: 999,
    status: "active",
  },
  {
    id: "p3",
    name: "Crédito Personal Express",
    description: "Préstamo personal con aprobación en 24 horas",
    price: 0,
    category: "Créditos",
    stock: 999,
    status: "active",
  },
  {
    id: "p4",
    name: "Seguro Automotriz",
    description: "Protección total para tu vehículo con cobertura amplia",
    price: 1800,
    category: "Seguros",
    stock: 999,
    status: "active",
  },
  {
    id: "p5",
    name: "Fondo de Ahorro Empresarial",
    description: "Solución de ahorro para empresas con beneficios fiscales",
    price: 10000,
    category: "Ahorro",
    stock: 999,
    status: "inactive",
  },
]

export const mockConversations: ChatConversation[] = [
  {
    id: "conv1",
    customer: mockCustomers[0],
    status: "pending",
    source: "Facebook Ads - Seguro de Vida",
    createdAt: "2026-01-28T09:30:00",
    lastMessage: "Hola, me gustaría más información sobre el seguro",
    messages: [
      {
        id: "m1",
        content: "Hola, vi su anuncio de seguro de vida y me interesa",
        sender: "customer",
        timestamp: "2026-01-28T09:30:00",
        senderName: "Ana Rodríguez",
      },
      {
        id: "m2",
        content: "¡Hola Ana! Bienvenida a Mercantiles. Nuestro seguro de vida Premium ofrece cobertura completa. ¿Te gustaría agendar una cita con un asesor?",
        sender: "bot",
        timestamp: "2026-01-28T09:30:15",
      },
      {
        id: "m3",
        content: "Prefiero hablar con una persona, tengo dudas específicas",
        sender: "customer",
        timestamp: "2026-01-28T09:31:00",
        senderName: "Ana Rodríguez",
      },
    ],
  },
  {
    id: "conv2",
    customer: mockCustomers[1],
    status: "active",
    source: "Google Ads - Inversiones",
    createdAt: "2026-01-28T10:15:00",
    lastMessage: "¿Cuál es el monto mínimo de inversión?",
    assignedTo: {
      id: "2",
      name: "María López",
      email: "maria@mercantiles.com",
      role: "agent",
      avatar: "ML",
    },
    messages: [
      {
        id: "m4",
        content: "Buenos días, quiero invertir pero tengo preguntas",
        sender: "customer",
        timestamp: "2026-01-28T10:15:00",
        senderName: "Pedro Sánchez",
      },
      {
        id: "m5",
        content: "¡Buenos días Pedro! Claro, con gusto te ayudo. ¿Qué tipo de inversión te interesa?",
        sender: "bot",
        timestamp: "2026-01-28T10:15:20",
      },
      {
        id: "m6",
        content: "Algo seguro, no quiero mucho riesgo",
        sender: "customer",
        timestamp: "2026-01-28T10:16:00",
        senderName: "Pedro Sánchez",
      },
      {
        id: "m7",
        content: "Hola Pedro, soy María de Mercantiles. Te atenderé personalmente. Para inversiones seguras te recomiendo nuestro Plan Básico con rendimiento garantizado del 8%.",
        sender: "agent",
        timestamp: "2026-01-28T10:20:00",
        senderName: "María López",
      },
      {
        id: "m8",
        content: "¿Cuál es el monto mínimo de inversión?",
        sender: "customer",
        timestamp: "2026-01-28T10:21:00",
        senderName: "Pedro Sánchez",
      },
    ],
  },
  {
    id: "conv3",
    customer: mockCustomers[2],
    status: "pending",
    source: "Instagram Ads - Crédito",
    createdAt: "2026-01-28T11:00:00",
    lastMessage: "Necesito un crédito urgente, ¿pueden ayudarme?",
    messages: [
      {
        id: "m9",
        content: "Hola, necesito un crédito urgente, ¿pueden ayudarme?",
        sender: "customer",
        timestamp: "2026-01-28T11:00:00",
        senderName: "Laura Fernández",
      },
      {
        id: "m10",
        content: "¡Hola Laura! Claro que sí. Nuestro Crédito Personal Express se aprueba en 24 horas. ¿Cuánto necesitas?",
        sender: "bot",
        timestamp: "2026-01-28T11:00:15",
      },
    ],
  },
]

export const mockChatbotRecords: ChatbotRecord[] = [
  {
    id: "r1",
    type: "appointment",
    customerId: "c1",
    customerName: "Ana Rodríguez",
    content: "Cita agendada para el 30 de enero a las 10:00 AM - Consulta sobre Seguro de Vida",
    createdAt: "2026-01-28T09:35:00",
    conversationId: "conv1",
    status: "pending",
  },
  {
    id: "r2",
    type: "quote",
    customerId: "c2",
    customerName: "Pedro Sánchez",
    content: "Cotización generada: Plan de Inversión Básico - $5,000 MXN inicial, rendimiento 8% anual",
    createdAt: "2026-01-28T10:25:00",
    conversationId: "conv2",
    status: "completed",
  },
  {
    id: "r3",
    type: "survey",
    customerId: "c4",
    customerName: "Roberto Díaz",
    content: "Encuesta de satisfacción completada: Calificación 4/5, Comentario: Buen servicio pero tiempos de espera largos",
    createdAt: "2026-01-27T15:00:00",
    conversationId: "conv4",
    status: "completed",
  },
  {
    id: "r4",
    type: "document",
    customerId: "c5",
    customerName: "Carmen Morales",
    content: "Documento generado: Contrato preliminar de Seguro Automotriz - Póliza #SA-2026-0128",
    createdAt: "2026-01-27T12:30:00",
    conversationId: "conv5",
    status: "pending",
  },
  {
    id: "r5",
    type: "appointment",
    customerId: "c3",
    customerName: "Laura Fernández",
    content: "Cita agendada para el 29 de enero a las 3:00 PM - Evaluación de crédito personal",
    createdAt: "2026-01-28T11:05:00",
    conversationId: "conv3",
    status: "pending",
  },
]
